-- Admin emails: only these can access /admin. Add your admin email(s) here.
CREATE TABLE IF NOT EXISTS admins (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Insert placeholder - replace with actual admin email in Supabase SQL Editor
INSERT INTO admins (email) VALUES ('admin@lorenaskitchen.com') ON CONFLICT (email) DO NOTHING;

-- RLS: users can only check if their own email is in admins
ALTER TABLE admins ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can read own admin status" ON admins;
CREATE POLICY "Users can read own admin status" ON admins FOR SELECT USING (auth.jwt() ->> 'email' = email);
