-- Feedback from homepage: star rating + comment, approved by admin before showing.
-- Run in Supabase SQL Editor if you want the feedback portal to work.

CREATE TABLE IF NOT EXISTS feedback (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rating int NOT NULL CHECK (rating >= 1 AND rating <= 5),
  content text,
  user_email text,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  meal_id bigint REFERENCES meals(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Optional: RLS so only authenticated admin can read/update
-- ALTER TABLE feedback ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Admin can manage feedback" ON feedback FOR ALL USING (auth.role() = 'authenticated');

COMMENT ON TABLE feedback IS 'Visitor feedback (star + comment). status=approved shows on homepage.';
