-- Visitors who register their email can use Contact & Suggestion forms.
-- Run in Supabase SQL Editor.

CREATE TABLE IF NOT EXISTS registered_emails (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_registered_emails_email ON registered_emails (email);

COMMENT ON TABLE registered_emails IS 'Emails that have registered to use Contact and Suggestion forms on the homepage.';
