-- Suggestions from homepage (e.g. "I'd love to see X again"). Admin approves to show on site.
CREATE TABLE IF NOT EXISTS suggestions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content text NOT NULL,
  user_email text,
  status text NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'approved', 'rejected')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_suggestions_status ON suggestions (status);
CREATE INDEX IF NOT EXISTS idx_suggestions_created_at ON suggestions (created_at DESC);

COMMENT ON TABLE suggestions IS 'Visitor meal suggestions. status=approved shows on homepage.';
